AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Plataforma serverless para recebimento e análise de avaliações.

Parameters:
  AdminEmail:
    Type: String
    Description: Email que receberá alertas de avaliações críticas
    NoEcho: true

Globals:
  Function:
    Runtime: java21
    Architectures:
      - x86_64
    Timeout: 30
    MemorySize: 1024
    LoggingConfig:
      LogFormat: JSON

Resources:

  AvaliacoesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: feedback-avaliacoes
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true

  AvaliacoesCriticasTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: feedback-avaliacoes-criticas

  AvaliacoesCriticasEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref AdminEmail
      TopicArn: !Ref AvaliacoesCriticasTopic

  ReceberAvaliacaoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: feedback-receber-avaliacao
      CodeUri: ReceberAvaliacaoFunction
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest

      Environment:
        Variables:
          MAIN_CLASS: br.com.techchallenge.feedback.FeedbackApplication
          SPRING_CLOUD_FUNCTION_DEFINITION: receberAvaliacao
          AVALIACOES_TABLE_NAME: !Ref AvaliacoesTable
          SNS_TOPIC_ARN: !Ref AvaliacoesCriticasTopic

      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref AvaliacoesTable

        - SNSPublishMessagePolicy:
            TopicName: !GetAtt AvaliacoesCriticasTopic.TopicName

      Events:
        ReceberAvaliacaoApi:
          Type: Api
          Properties:
            Path: /avaliacoes
            Method: post

Outputs:

  AvaliacaoApiUrl:
    Description: Endpoint para envio de avaliações
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/avaliacoes"

  AvaliacoesTableName:
    Description: Nome da tabela de avaliações
    Value: !Ref AvaliacoesTable

  AvaliacoesCriticasTopicArn:
    Description: ARN do tópico de alertas críticos
    Value: !Ref AvaliacoesCriticasTopic

  ReceberAvaliacaoFunctionArn:
    Description: ARN da função de recebimento
    Value: !GetAtt ReceberAvaliacaoFunction.Arn